import { melodyNote } from 'src/components/models';

export const internationaleMelody: melodyNote[] = [
  { pitch: 4, duration: 3 / 4 },
  { pitch: 2, duration: 1 / 4 },
  { pitch: 0, duration: 2 },
  { pitch: -5, duration: 3 / 2 },
  { pitch: -3, duration: 1 / 2 },
  { pitch: -3, duration: 3 },
  //{ pitch: -7, duration: 1 },
  { pitch: 2, duration: 3 / 4 },
  { pitch: 0, duration: 1 / 4 },
  { pitch: -1, duration: 2 },
  { pitch: -3, duration: 1 },
  { pitch: -5, duration: 1 },
  { pitch: -5, duration: 3 },
  { pitch: -5, duration: 1 },
  { pitch: 4, duration: 2 },
  { pitch: 2, duration: 1 },
  { pitch: 0, duration: 1 },
  { pitch: 0, duration: 7 / 2 },
  { pitch: -1, duration: 1 / 2 },
  { pitch: -3, duration: 3 / 2 },
  { pitch: -4, duration: 1 / 2 },
  { pitch: -3, duration: 1 },
  { pitch: 2, duration: 1 },
  { pitch: 2, duration: 3 },

  { pitch: 4, duration: 3 / 4 },
  { pitch: 2, duration: 1 / 4 },
  { pitch: 0, duration: 2 },
  { pitch: -5, duration: 3 / 2 },
  { pitch: -3, duration: 1 / 2 },
  { pitch: -3, duration: 3 },
  //{ pitch: -7, duration: 1 },
  { pitch: 2, duration: 3 / 4 },
  { pitch: 0, duration: 1 / 4 },
  { pitch: -1, duration: 2 },
  { pitch: 0, duration: 1 },
  { pitch: -5, duration: 1 },
  { pitch: 4, duration: 3 },
  { pitch: 4, duration: 1 },
  { pitch: 7, duration: 2 },
  { pitch: 5, duration: 1 },
  { pitch: 4, duration: 1 },
  { pitch: 2, duration: 1 / 2 },
  { pitch: 1, duration: 1 / 2 },
  { pitch: 2, duration: 1 / 2 },
  { pitch: 4, duration: 1 / 2 },
  { pitch: 5, duration: 3 / 2 },
  { pitch: 5, duration: 1 / 2 },
  { pitch: 4, duration: 3 / 2 },
  { pitch: 4, duration: 1 / 2 },
  { pitch: 2, duration: 3 / 2 },
  { pitch: 2, duration: 1 / 2 },
  { pitch: 0, duration: 1 },
];
