import { melodyNote } from 'src/components/models';

export const onEstLaMelody: melodyNote[] = [
  { pitch: 4, duration: 1 / 2 },
  { pitch: 2, duration: 1 / 2 },
  { pitch: 0, duration: 2 },
  { pitch: 0, duration: 1 / 2 },
  { pitch: 4, duration: 1 / 2 },
  { pitch: 7, duration: 2 },
  { pitch: 4, duration: 1 / 2 },
  { pitch: 5, duration: 1 / 2 },
  { pitch: 7, duration: 1 / 2 },
  { pitch: 7, duration: 1 / 2 },
  { pitch: 7, duration: 1 / 2 },
  { pitch: 7, duration: 1 / 2 },
  { pitch: 7, duration: 1 / 2 },
  { pitch: 5, duration: 1 / 2 },
  { pitch: 4, duration: 1 / 2 },
  { pitch: 5, duration: 1 / 2 },
  { pitch: 2, duration: 2 },
  { pitch: 2, duration: 1 / 2 },
  { pitch: 4, duration: 1 / 2 },
  { pitch: 5, duration: 1 / 2 },
  { pitch: 5, duration: 1 / 2 },
  { pitch: 5, duration: 1 / 2 },
  { pitch: 5, duration: 1 / 2 },
  { pitch: 5, duration: 1 },
  { pitch: 4, duration: 1 / 2 },
  { pitch: 2, duration: 1 / 2 },
  { pitch: 4, duration: 1 / 2 },
  { pitch: 4, duration: 1 / 2 },
  { pitch: 4, duration: 1 / 2 },
  { pitch: 4, duration: 1 / 2 },
  { pitch: 4, duration: 1 },
  { pitch: 2, duration: 1 / 2 },
  { pitch: 0, duration: 1 / 2 },
  { pitch: 2, duration: 1 / 2 },
  { pitch: 2, duration: 1 / 2 },
  { pitch: 2, duration: 1 / 2 },
  { pitch: 2, duration: 1 / 2 },
  { pitch: 2, duration: 1 / 2 },
  { pitch: 0, duration: 1 / 2 },
  { pitch: -1, duration: 1 / 2 },
  { pitch: 2, duration: 1 / 2 },
  { pitch: 0, duration: 1 },
];
